port: 4001
baseurl: "http://www.chrisabani.com"
sitename: Chris Abani
# source: ./content
permalink: pretty
future: true   # This will tell jekyll to not display future posts
markdown: redcarpet
redcarpet:
  extensions: ['autolink', 'smart']
exclude: ['README.md','Gemfile','links.jsonp', 'assets/scss', '/assets/less/', 'CNAME', 'assets/css/bower_components']
include: ['_pages']
relative_permalinks: false
prose:
  siteurl: 'http://www.chrisbani.com'
  #rooturl: '_posts'
  site: 
  media: 'assets/img'
  metadata:
    _posts/books:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Book Title"
          value: "Book Title"
      - name: "subtitle"
        field:
          element: "text"
          label: "Subtitle"
      - name: "name"
        field:
          element: "text"
          label: "Name/Slug"
          help: "lowercase title with dashes between words"
          placeholder: "the-title-of-the-book"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          help: "/book/name-from-above"
          placeholder: "/book/name-from-above"
      - name: "pub_date"
        field:
          element: "text"
          label: "Publication Date"
          help: "format: YYYY-MM-DD"
          placeholder: "2014-01-01"
      - name: "isbn"
        field:
          element: "text"
          label: "ISBN"
          help: "13 Digit with no spaces"
          placeholder: "978xxxxxxxxxx"
      - name: "isbn_digital"
        field:
          element: "text"
          label: "ISBN Digital"
          help: "13 Digit with no spaces"
          placeholder: "978xxxxxxxxxx"
      - name: "asin"
        field:
          element: "text"
          label: "Amazon ASIN"
          help: "10 Digit with no spaces"
      - name: "asin_kindle"
        field:
          element: "text"
          label: "Amazon Kindle ASIN"
          help: "10 Digit with no spaces"
      - name: "publisher"
        field:
          element: "text"
          label: "Publisher"
      - name: "cover_image"
        field:
          element: "text"
          label: "Cover Image"
          help: "if different than isbn.jpg"
          placeholder: "name.jpg"
      - name: "category"
        field:
          element: "hidden"
          value: "book"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Book Category"
          placeholder: "Choose Tags"
          options:
            - name: "Fiction"
              value: "fiction"
            - name: "Poetry"
              value: "poetry"
            - name: "Screenplay"
              value: "screenplay"
      - name: "layout"
        field:
          element: "hidden"
          value: "book"
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "category"
        field:
          element: "hidden"
          value: "posts"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Title"
          value: "Title"
      - name: published
        field:
          element: "text"
          label: "Status"
          help: "Change to false if you don't want the post to be published"
          value: true
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
          options:
            - name: "Video"
              value: "video"
            - name: "News"
              value: "news"
            - name: "Books"
              value: "books"
    _pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Title"
          value: "Title"
      - name: permalink
        field:
          element: "text"
          label: "Link"
          help: "/page-name/"
      - name: show_in_menu
        field:
          element: "select"
          label: "Show in Menu?"
          options:
            - name: "True"
              value: 'true'
            - name: "False"
              value: 'false'
